% create phantom with 2D spectral encoding

addpath("data","solvers","utilities","ini2struct")

%Phantom generation
create_phantom('acqfile','data/acq_phantom.txt', ...
    'spectfile','data/Phantom_spect.txt', ...
    'outfolder','Phantom2D','multislice',1) %or create_phantom

plot_beta_sweep('imgfile','Phantom2D/Phantom_data.mat', ...
    'betafile','data/betafile_phantom2d.txt', ...
    'spect_infofile','Phantom2D/Phantom_spectrum_info.mat', ...
    'outprefix','Phantom2D/Phantom_data_ladmm_spect', ...
    'configfile', 'demos/Phantom2D_ladmm.ini','spatmaskfile', ...
    'Phantom2D/Phantom_mask_beta_calc.mat','file_types','png');

%spectrum Estimation --ladmm
estimate_spectra('imgfile','Phantom2D/Phantom_data.mat', ...
    'spect_infofile', 'Phantom2D/Phantom_spectrum_info.mat', ...
    'outprefix','Phantom2D/Phantom2D_data_ladmm_spect', ...
    'configfile','demos/Phantom2D_ladmm.ini', ...
    'spatmaskfile','Phantom2D/Phantom_mask.mat')

%spectrum Estimation --admm
estimate_spectra('imgfile','Phantom2D/Phantom_data.mat', ...
    'spect_infofile', 'Phantom2D/Phantom_spectrum_info.mat', ...
    'outprefix','Phantom2D/Phantom2D_data_admm_spect.mat', ...
    'configfile','demos/Phantom2D_admm.ini', ...
    'spatmaskfile','Phantom2D/Phantom_mask.mat','cost_calc',1)

%spectrum Estimation --nnls
estimate_spectra('imgfile','Phantom2D/Phantom_data.mat', ...
    'spect_infofile', 'Phantom2D/Phantom_spectrum_info.mat', ...
    'outprefix','Phantom2D/Phantom2D_data_nnls_spect.mat', ...
    'configfile','demos/Phantom2D_nnls.ini', ...
    'spatmaskfile','Phantom2D/Phantom_mask.mat')

%plot Average spectra
plot_avg_spectra('spect_imfile','Phantom2D/Phantom2D_data_ladmm_spect.mat', ...
    'spatmaskfile', 'Phantom2D/Phantom_mask.mat', ...
    'outprefix','Phantom2D/Phantom2D_data_ladmm_avg_spectra', ...
   'cbar','0','color','jet','linewidth',3,'ax_scale','log', ...
    'ax_lims',"[ 0.05 2 10 200]",'nlevel',15, 'file_types', {'png','pdf'});

% Plot spectroscopic image
plot_spect_im('spect_imfile','Phantom2D/Phantom2D_data_ladmm_spect.mat', ...
    'imgfile','Phantom2D/Phantom_data.mat', ...
    'spatmaskfile','Phantom2D/Phantom_mask.mat', ...
    'outprefix','Phantom2D/Phantom2D_data_spectroscopic_Im', ...
    'ax_scale','log','ax_lims','[0.01 1.5 10 100]','color','jet',...
    'threshold','.25','linewidth',3, ...
    'enc_idx',"3",'file_types',{'png'})

% Plot component Maps
plot_comp_maps('spect_imfile','Phantom2D/Phantom2D_data_ladmm_spect.mat','outprefix', ...
    'Phantom2D/Phantom2D_data_component_maps','spectmaskfile', ...
    'data/Phantom2D_spectrum_mask.mat', ...
    'cbar','1','weights','[1.4 1 1]','color','data/four_color.mat')

