% create phantom with 1D spectral encoding

addpath("data","solvers","utilities","ini2struct")

%Phantom generation
create_phantom('acqfile','data/acq_phantom1D.txt','spectfile','data/Phantom1D_spect.txt', ...
    'outfolder','Phantom1D','multislice',0) %or create_phantom

plot_beta_sweep('imgfile','Phantom1D/Phantom_data.mat','betafile','data/betafile_phantom1d.txt','spect_infofile','Phantom1D/Phantom_spectrm_info.mat', ...
    'outprefix','Phantom1D/Phantom_data_ladmm_spect','configfile', 'demos/Phantom1D_ladmm.ini','spatmaskfile', ...
    'Phantom1D/Phantom_mask_beta_calc.mat','file_types','png');

%spectrum Estimation --ladmm
estimate_spectra('imgfile','Phantom1D/Phantom_data.mat','spect_infofile', 'Phantom1D/Phantom_spectrm_info.mat', ...
    'outprefix','Phantom1D/Phantom1D_data_ladmm_spect.mat','configfile','demos/Phantom1D_ladmm.ini','spatmaskfile','Phantom1D/Phantom_mask.mat')

%spectrum Estimation --admm
estimate_spectra('imgfile','Phantom1D/Phantom_data.mat','spect_infofile', 'Phantom1D/Phantom_spectrm_info.mat', ...
    'outprefix','Phantom1D/Phantom1D_data_admm_spect.mat','configfile','demos/Phantom1D_admm.ini','spatmaskfile','Phantom1D/Phantom_mask.mat')

%spectrum Estimation --nnls
estimate_spectra('imgfile','Phantom1D/Phantom_data.mat','spect_infofile', 'Phantom1D/Phantom_spectrm_info.mat', ...
    'outprefix','Phantom1D/Phantom1D_data_nnls_spect.mat','configfile','demos/Phantom1D_nnls.ini','spatmaskfile','Phantom1D/Phantom_mask.mat')

%plot Average spectra
plot_avg_spectra('spect_imfile','Phantom1D/Phantom1D_data_ladmm_spect.mat', 'spatmaskfile', 'Phantom1D/Phantom_mask.mat', ...
    'outprefix','Phantom1D/Phantom1D_data_ladmm_avg_spectra','linewidth',3,'ax_scale','log','color','g','cbar',1, ...
    'ax_lim',"[10 200]", 'file_types', {'png','pdf'});

% Plot spectroscopic image
plot_spect_im('spect_imfile','Phantom1D/Phantom1D_data_ladmm_spect.mat', ...
    'imgfile','Phantom1D/Phantom_data.mat','spatmaskfile','Phantom1D/Phantom_mask.mat', ...
    'outprefix','Phantom1D/Phantom1D_data_spectroscopic_Im','threshold',.2, ...
    'linewidth',1,'enc_idx',8,'ax_scale',{'log'},'color','g', ...
    'ax_lim',"[10 200]",'file_types',{'png','jpg'})

% Plot component Maps
plot_comp_maps('spect_imfile','Phantom1D/Phantom1D_data_ladmm_spect.mat', ...
    'spectmaskfile','data/Phantom1D_spectrm_mask.mat', ...
    'color','data/four_color.mat','outprefix', 'Phantom1D/Phantom1D_component_maps', ...
    'cbar',0,'weights','[1 3]');
